feat: merge upstream (#3)
* perf: Drawpool 3.1

more stability in FPS

* setting m_effectAlpha, m_missileAlpha to 1.f

* fix: display density on mapview

* feat: hud scale

* fix: Interface Anchors (#862)

* feat: support directx

* improve: use egl v3

* small change in gc

* fix: memory leak in controller

* improve: organization of the project structure

* add new config to draw covered things

There are projects where this system doesn't work very well, so if your project is one of those, just set it to true to fix the tiles that aren't being drawn.

* feat: update background image and startup sound to use 13.40 cip files. Adjustments in options buttons order and logout button icon. (#865)

* update UIGraph (need test)

* fix shader warning

* fix: console error due to shaders

* draw-covered-things to false

Note: Setting false will not draw objects that the client understands are covered. If for some reason a tile is not being drawn because your game is custom, set this property to true and this issue will be resolved.

* baseline updated (update your vcpkg)

git pull

* Revert "baseline updated (update your vcpkg)"

This reverts commit 8dda995272dd26d8bfce768f587c282b2cba321b.

* fix: #867

* feat: extractTexture in framebuffer, Arch SS2 by default and cleanup

* fix: inverted texture in extractTexture

* html: support tag img

* perf: reducing locking, thus increasing performance a little.

* fix draw shader

* prevent crash in static text

* improve: add lua call protection

* perf: improve propagateOnMouseMove

* fix: bot item ondrop and analyzer loot channel (#887)

* fix: outfit size , prevent ERROR: invalid thing (#884)

Co-authored-by: Rodrigo Paixão <god.rodrigo@hotmail.com>

* improve: HTTP login error handling to display login.php error messages (#886)

* fix: compilation error on some pcs

* feat: full cyclopedia module (#868)

* fix: game_store bugs. fix: #873 (#874)

* feat: Minimap GM teleport ( ctrl +shift + click on minimap) (#885)

Co-authored-by: Luan Luciano <luanluciano@outlook.com>

* support "Mage" vocation (#882)

several OT servers merge MS/ED vocation into a Mage vocation having the best features of both MS and ED.

Without this fix, on those servers, vBot would constantly error out with Error: (...) concatenat voc: a nil value

* fix (#900)

* improve parseOpenContainer and fix error with decoration kit (#890)

* fix: optional display rarity colors in items . feature GameColorizedLootValue 12.00 (#896)

* fix: crash getItems (#892)

* looting blacklist (#881)

When "loot every item" is off, it will loot everything in the loot list.

When "loot every item" is on, it will loot everything that is not in the loot list, effectively making the loot list a blacklist when "loot every item" is on.

* Fix black and red squares behaviors (#902)


* Fix squares:
- Set black squares color to 1 instead of 0 so it's not treated as alpha
- Fix creaturesMark logic so red squares don't disappear when attacking and black squares show when attacked

* feat: display tier UI (GameThingUpgradeClassification) (#895)

* feat: Vips Groups | fix issue: #730 (#908)

* fix: spacing for align bottom vertical layouts (#909)

* Fix: #901

---------

Co-authored-by: Renato Machado <mehahx@gmail.com>
Co-authored-by: SkullzOTS <86809689+SkullzOTS@users.noreply.github.com>
Co-authored-by: Luan Luciano <luanluciano@outlook.com>
Co-authored-by: Felipe Muniz <felipe.silva@virtus.ufcg.edu.br>
Co-authored-by: Rodrigo Paixão <god.rodrigo@hotmail.com>
Co-authored-by: kokekanon <114332266+kokekanon@users.noreply.github.com>
Co-authored-by: divinity76 <divinity76@gmail.com>
Co-authored-by: divinity76 <hans@loltek.net>
Co-authored-by: OT Archive <112215823+OTArchive@users.noreply.github.com>
Co-authored-by: Marcin Jałocha <nekiro.dev@gmail.com>