fix: UI creature sizes outfits (#1335)
* revert #1303

* Revert "revert #1303"

This reverts commit 719781a234d465643ae7af62e8af6a05c76f6d39.

* fix: Outfits window, Selection preview, charselect

* Warning fix

* Fix luaCallLuaField warnings

* fix: tks Nekiro - Outfit List

* fix: shaders,effects,wings,auras,mounts

* fix small error console

* Update outfit.lua

* Fix error of nil attach effects oldprotocol

ERROR: protected lua call failed: LUA ERROR:
/game_attachedeffects/attachedeffects.lua:73: attempt to index a nil value

* Fixed issues to creaturePreview pos bars